mds:
  contexts:
    - name: mds-proxy-1
      port: 8888
      heartbeatIntervalInMs: 55000
      version: 5.0
      handshakeStrategy: ACCEPT
      grpc:
        outputProtoDir: ./protos/mds-proxy-1/
        port: 8889
server:
  port: 9999